/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        './pages/**/*.{ts,tsx}',
        './components/**/*.{ts,tsx}',
        './app/**/*.{ts,tsx}',
        './src/**/*.{ts,tsx}',
    ],
    prefix: "",
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "#006c5d",
                    foreground: "#e3fff6",
                },
                secondary: {
                    DEFAULT: "#56606e",
                    foreground: "#f7f9ff",
                },
                destructive: {
                    DEFAULT: "#a83836",
                    foreground: "#fff7f6",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                "primary-fixed-dim": "#6fe9d1",
                "tertiary-container": "#b6ebfd",
                "surface": "#f8f9fb",
                "tertiary-fixed-dim": "#a9dcef",
                "surface-tint": "#006c5d",
                "error": "#a83836",
                "on-primary-container": "#005d50",
                "on-secondary-fixed-variant": "#525c6a",
                "primary-fixed": "#7ef7de",
                "primary-dim": "#005e51",
                "tertiary-fixed": "#b6ebfd",
                "surface-container-high": "#e5e9ec",
                "inverse-surface": "#0c0f10",
                "secondary-fixed-dim": "#cbd5e6",
                "on-secondary-container": "#485260",
                "on-primary-fixed-variant": "#006859",
                "secondary-fixed": "#d9e3f4",
                "on-primary-fixed": "#00483e",
                "surface-variant": "#dee3e7",
                "surface-dim": "#d5dbdf",
                "error-dim": "#67040d",
                "on-secondary-fixed": "#36404d",
                "on-surface": "#2d3337",
                "outline-variant": "#adb3b7",
                "surface-container-low": "#f1f4f7",
                "on-tertiary-fixed": "#054655",
                "surface-container-highest": "#dee3e7",
                "on-surface-variant": "#5a6064",
                "surface-container": "#ebeef1",
                "on-background": "#2d3337",
                "tertiary": "#316676",
                "on-tertiary-container": "#225868",
                "inverse-primary": "#84fde4",
                "surface-container-lowest": "#ffffff",
                "on-tertiary": "#f1fbff",
                "outline": "#767b7f",
                "surface-bright": "#f8f9fb",
                "primary-container": "#7ef7de",
                "on-error": "#fff7f6",
                "tertiary-dim": "#245a69",
                "on-secondary": "#f7f9ff",
                "on-tertiary-fixed-variant": "#2d6272",
                "secondary-container": "#d9e3f4",
                "error-container": "#fa746f",
                "secondary-dim": "#4a5462",
                "inverse-on-surface": "#9b9d9f",
                "on-error-container": "#6e0a12",
                "on-primary": "#e3fff6",
            },
            fontFamily: {
                headline: ["Manrope", "sans-serif"],
                body: ["Manrope", "sans-serif"],
                label: ["Inter", "sans-serif"],
                manrope: ["Manrope", "sans-serif"],
                inter: ["Inter", "sans-serif"],
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
}
